In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
from google.colab import files
uploaded = files.upload()

Saving cards_data.csv to cards_data (1).csv
Saving transactions_sample.csv to transactions_sample.csv
Saving users_data.csv to users_data.csv

In [13]:
users = pd.read_csv('users_data.csv')

cards = pd.read_csv('cards_data.csv')

transactions = pd.read_csv('transactions_sample.csv')

In [15]:
users.shape

cards.shape

transactions.shape

(200000, 12)

In [20]:
users.head()

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,$37891,$77254,$191349,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,$22681,$33483,$196,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,$163145,$249925,$202328,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,$53797,$109687,$183855,675,1

In [21]:

cards.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,07/2003,2004,No
3,42,825,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,01/2003,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,09/2008,2009,No

In [22]:
transactions.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,11978328,2012-11-23 16:03:00,619,3348,$263.43,Swipe Transaction,54850,Austin,MN,55912.0,4814,NaN
1,11363233,2012-07-07 13:57:00,456,4576,$38.26,Swipe Transaction,68135,Cape Coral,FL,33909.0,5411,NaN
2,8117710,2010-06-10 16:59:00,209,4676,$52.57,Swipe Transaction,81833,El Paso,TX,79928.0,5912,NaN
3,12606562,2013-04-13 12:08:00,1605,1133,$40.00,Swipe Transaction,27092,Amelia,OH,45102.0,4829,NaN
4,12628171,2013-04-18 10:00:00,144,5247,$4.58,Swipe Transaction,44578,Arkadelphia,AR,71923.0,5812,NaN

In [25]:
users.columns = (
    users.columns
    .str.lower()
    .str.replace(' ','_')
)

In [26]:
cards.columns = (
    cards.columns
    .str.lower()
    .str.replace(' ','_')
)

In [27]:

transactions.columns = (
    transactions.columns
    .str.lower()
    .str.replace(' ','_')
)

In [28]:
users.columns

Index(['id', 'current_age', 'retirement_age', 'birth_year', 'birth_month',
       'gender', 'address', 'latitude', 'longitude', 'per_capita_income',
       'yearly_income', 'total_debt', 'credit_score', 'num_credit_cards'],
      dtype='object')

In [29]:

transactions.columns

Index(['id', 'date', 'client_id', 'card_id', 'amount', 'use_chip',
       'merchant_id', 'merchant_city', 'merchant_state', 'zip', 'mcc',
       'errors'],
      dtype='object')

In [30]:
cards.columns

Index(['id', 'client_id', 'card_brand', 'card_type', 'card_number', 'expires',
       'cvv', 'has_chip', 'num_cards_issued', 'credit_limit', 'acct_open_date',
       'year_pin_last_changed', 'card_on_dark_web'],
      dtype='object')

In [33]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 2000 non-null   int64
 1   current_age        2000 non-null   int64
 2   retirement_age     2000 non-null   int64
 3   birth_year         2000 non-null   int64
 4   birth_month        2000 non-null   int64
 5   gender             2000 non-null   object
 6   address            2000 non-null   object
 7   latitude           2000 non-null   float64
 8   longitude          2000 non-null   float64
 9   per_capita_income  2000 non-null   object
 10  yearly_income      2000 non-null   object
 11  total_debt         2000 non-null   object
 12  credit_score       2000 non-null   int64
 13  num_credit_cards   2000 non-null   int64
dtypes: float64(2), int64(7), object(5)
memory usage: 218.9+ KB

In [34]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              200000 non-null  int64
 1   date            200000 non-null  object
 2   client_id       200000 non-null  int64
 3   card_id         200000 non-null  int64
 4   amount          200000 non-null  object
 5   use_chip        200000 non-null  object
 6   merchant_id     200000 non-null  int64
 7   merchant_city   200000 non-null  object
 8   merchant_state  176513 non-null  object
 9   zip             175168 non-null  float64
 10  mcc             200000 non-null  int64
 11  errors          3157 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 18.3+ MB

In [35]:
cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6146 non-null   int64
 1   client_id              6146 non-null   int64
 2   card_brand             6146 non-null   object
 3   card_type              6146 non-null   object
 4   card_number            6146 non-null   int64
 5   expires                6146 non-null   object
 6   cvv                    6146 non-null   int64
 7   has_chip               6146 non-null   object
 8   num_cards_issued       6146 non-null   int64
 9   credit_limit           6146 non-null   object
 10  acct_open_date         6146 non-null   object
 11  year_pin_last_changed  6146 non-null   int64
 12  card_on_dark_web       6146 non-null   object
dtypes: int64(6), object(7)
memory usage: 624.3+ KB

In [36]:
users.isnull().sum()

id                   0
current_age          0
retirement_age       0
birth_year           0
birth_month          0
gender               0
address              0
latitude             0
longitude            0
per_capita_income    0
yearly_income        0
total_debt           0
credit_score         0
num_credit_cards     0
dtype: int64

In [37]:
transactions.isnull().sum()

id                     0
date                   0
client_id              0
card_id                0
amount                 0
use_chip               0
merchant_id            0
merchant_city          0
merchant_state     23487
zip                24832
mcc                    0
errors            196843
dtype: int64

In [38]:
cards.isnull().sum()

id                       0
client_id                0
card_brand               0
card_type                0
card_number              0
expires                  0
cvv                      0
has_chip                 0
num_cards_issued         0
credit_limit             0
acct_open_date           0
year_pin_last_changed    0
card_on_dark_web         0
dtype: int64

In [41]:
users['per_capita_income'] = users['per_capita_income'].replace(r'[\$,]', '', regex=True).astype(float)
users['yearly_income'] = users['yearly_income'].replace(r'[\$,]', '', regex=True).astype(float)
users['total_debt'] = users['total_debt'].replace(r'[\$,]', '', regex=True).astype(float)

In [42]:
cards['credit_limit'] = cards['credit_limit'].replace(r'[\$,]', '', regex=True).astype(float)

In [43]:
transactions['amount'] = transactions['amount'].replace(r'[\$,]', '', regex=True).astype(float)

In [44]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 2000 non-null   int64
 1   current_age        2000 non-null   int64
 2   retirement_age     2000 non-null   int64
 3   birth_year         2000 non-null   int64
 4   birth_month        2000 non-null   int64
 5   gender             2000 non-null   object
 6   address            2000 non-null   object
 7   latitude           2000 non-null   float64
 8   longitude          2000 non-null   float64
 9   per_capita_income  2000 non-null   float64
 10  yearly_income      2000 non-null   float64
 11  total_debt         2000 non-null   float64
 12  credit_score       2000 non-null   int64
 13  num_credit_cards   2000 non-null   int64
dtypes: float64(5), int64(7), object(2)
memory usage: 218.9+ KB

In [45]:
cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6146 non-null   int64
 1   client_id              6146 non-null   int64
 2   card_brand             6146 non-null   object
 3   card_type              6146 non-null   object
 4   card_number            6146 non-null   int64
 5   expires                6146 non-null   object
 6   cvv                    6146 non-null   int64
 7   has_chip               6146 non-null   object
 8   num_cards_issued       6146 non-null   int64
 9   credit_limit           6146 non-null   float64
 10  acct_open_date         6146 non-null   object
 11  year_pin_last_changed  6146 non-null   int64
 12  card_on_dark_web       6146 non-null   object
dtypes: float64(1), int64(6), object(6)
memory usage: 624.3+ KB

In [46]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              200000 non-null  int64
 1   date            200000 non-null  object
 2   client_id       200000 non-null  int64
 3   card_id         200000 non-null  int64
 4   amount          200000 non-null  float64
 5   use_chip        200000 non-null  object
 6   merchant_id     200000 non-null  int64
 7   merchant_city   200000 non-null  object
 8   merchant_state  176513 non-null  object
 9   zip             175168 non-null  float64
 10  mcc             200000 non-null  int64
 11  errors          3157 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.3+ MB

In [47]:
transactions['date'] = pd.to_datetime(transactions['date'])

In [49]:
cards['acct_open_date'] = pd.to_datetime(cards['acct_open_date'],errors='coerce')

In [50]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              200000 non-null  int64
 1   date            200000 non-null  datetime64[ns]
 2   client_id       200000 non-null  int64
 3   card_id         200000 non-null  int64
 4   amount          200000 non-null  float64
 5   use_chip        200000 non-null  object
 6   merchant_id     200000 non-null  int64
 7   merchant_city   200000 non-null  object
 8   merchant_state  176513 non-null  object
 9   zip             175168 non-null  float64
 10  mcc             200000 non-null  int64
 11  errors          3157 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(5), object(4)
memory usage: 18.3+ MB

In [51]:
cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6146 non-null   int64
 1   client_id              6146 non-null   int64
 2   card_brand             6146 non-null   object
 3   card_type              6146 non-null   object
 4   card_number            6146 non-null   int64
 5   expires                6146 non-null   object
 6   cvv                    6146 non-null   int64
 7   has_chip               6146 non-null   object
 8   num_cards_issued       6146 non-null   int64
 9   credit_limit           6146 non-null   float64
 10  acct_open_date         6146 non-null   datetime64[ns]
 11  year_pin_last_changed  6146 non-null   int64
 12  card_on_dark_web       6146 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(6), object(5)
memory usage: 624.3+ KB

In [52]:
transactions['errors'] = transactions['errors'].fillna('No Error')

In [55]:
transactions['merchant_state'] = transactions['merchant_state'].fillna('Unknown')

In [53]:
transactions['zip'] = transactions['zip'].fillna(-1)

In [56]:
transactions.isnull().sum()

id                0
date              0
client_id         0
card_id           0
amount            0
use_chip          0
merchant_id       0
merchant_city     0
merchant_state    0
zip               0
mcc               0
errors            0
dtype: int64

In [58]:
transactions['year'] = transactions['date'].dt.year

In [59]:
transactions['month'] = transactions['date'].dt.month_name()

In [61]:
transactions['month_num'] = transactions['date'].dt.month

In [62]:
transactions['weekday'] = transactions['date'].dt.day_name()

In [63]:
transactions['hour'] = transactions['date'].dt.hour

In [64]:
transactions['is_weekend'] = transactions['weekday'].isin(['Saturday','Sunday'])

In [65]:
transactions.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors,year,month,month_num,weekday,hour,is_weekend
0,11978328,2012-11-23 16:03:00,619,3348,263.43,Swipe Transaction,54850,Austin,MN,55912.0,4814,No Error,2012,November,11,Friday,16,False
1,11363233,2012-07-07 13:57:00,456,4576,38.26,Swipe Transaction,68135,Cape Coral,FL,33909.0,5411,No Error,2012,July,7,Saturday,13,True
2,8117710,2010-06-10 16:59:00,209,4676,52.57,Swipe Transaction,81833,El Paso,TX,79928.0,5912,No Error,2010,June,6,Thursday,16,False
3,12606562,2013-04-13 12:08:00,1605,1133,40.00,Swipe Transaction,27092,Amelia,OH,45102.0,4829,No Error,2013,April,4,Saturday,12,True
4,12628171,2013-04-18 10:00:00,144,5247,4.58,Swipe Transaction,44578,Arkadelphia,AR,71923.0,5812,No Error,2013,April,4,Thursday,10,False

In [66]:
transactions['amount'].describe()

count    200000.000000
mean         43.013860
std          81.609802
min        -499.000000
25%           8.900000
50%          28.890000
75%          63.540000
max        3599.300000
Name: amount, dtype: float64

In [67]:
transactions['use_chip'].unique()

array(['Swipe Transaction', 'Chip Transaction', 'Online Transaction'],
      dtype=object)

In [68]:
cards['card_type'].unique()

array(['Debit', 'Credit', 'Debit (Prepaid)'], dtype=object)

In [69]:
cards['card_brand'].unique()

array(['Visa', 'Mastercard', 'Discover', 'Amex'], dtype=object)

In [70]:
transactions['errors'].unique()

array(['No Error', 'Insufficient Balance', 'Technical Glitch', 'Bad PIN',
       'Bad Card Number', 'Bad CVV', 'Bad Zipcode', 'Bad Expiration',
       'Bad CVV,Insufficient Balance',
       'Bad Expiration,Insufficient Balance',
       'Bad Card Number,Insufficient Balance',
       'Insufficient Balance,Technical Glitch',
       'Bad PIN,Insufficient Balance', 'Bad Card Number,Bad CVV'],
      dtype=object)

In [71]:
users.duplicated().sum()

np.int64(0)

In [72]:
cards.duplicated().sum()

np.int64(0)

In [73]:
transactions.duplicated().sum()

np.int64(0)

In [74]:
customer_metrics = transactions.groupby('client_id').agg({'amount':['sum','mean','count','std']})

In [75]:
customer_metrics.columns = [
    'total_spend',
    'avg_spend',
    'transaction_count',
    'spending_volatility'
]

In [76]:
customer_metrics = customer_metrics.reset_index()

In [77]:
customer_metrics.head()

   client_id  total_spend  avg_spend  transaction_count  spending_volatility
0          0     10182.75  50.161330                203            93.467215
1          1      5741.30  39.595172                145            66.538118
2          2      4631.68  28.948000                160            43.631100
3          3      4706.81  48.028673                 98            20.802682
4          4      7959.88  41.030309                194            66.551152

In [78]:
customer_metrics.describe()

,client_id,total_spend,avg_spend,transaction_count,spending_volatility
count,1219.000000,1219.000000,1219.000000,1219.000000,1219.000000
mean,1004.916325,7057.237006,44.057033,164.068909,75.781785
std,582.384462,4573.032167,21.321091,85.399151,36.135867
min,0.000000,432.970000,4.326486,7.000000,8.998445
25%,496.500000,3921.645000,30.698926,107.000000,53.575667
50%,1019.000000,6011.560000,40.785932,147.000000,67.617471
75%,1514.500000,9083.590000,53.634087,202.500000,90.091026
max,1998.000000,39686.150000,407.171429,729.000000,609.362766

In [79]:
customer_metrics['engagement_score'] = (customer_metrics['transaction_count'] * 0.6 + customer_metrics['avg_spend'] * 0.4)

In [83]:
customer_metrics['spending_tier'] = pd.cut(
    customer_metrics['total_spend'],
    bins=[0,3000,7000,15000,40000],
    labels=[
        'Low Spender',
        'Moderate Spender',
        'High Spender',
        'Premium Spender'
    ]
)

In [84]:
customer_metrics['spending_tier'].value_counts()

spending_tier
Moderate Spender    568
High Spender        403
Low Spender         172
Premium Spender      76
Name: count, dtype: int64

In [85]:
customer_metrics['volatility_level'] = pd.cut(
    customer_metrics['spending_volatility'],
    bins=[0,50,200,500,100000],
    labels=[
        'Stable',
        'Moderate',
        'Irregular',
        'Highly Volatile'
    ]
)

In [86]:
customer_metrics['volatility_level'].value_counts()

volatility_level
Moderate           969
Stable             243
Irregular            6
Highly Volatile      1
Name: count, dtype: int64

In [87]:
customer_metrics['wellness_score'] = (customer_metrics['avg_spend'] * 0.3 + customer_metrics['transaction_count'] * 0.4 - customer_metrics['spending_volatility'] * 0.2)

In [88]:
customer_metrics[
    [
        'client_id',
        'wellness_score',
        'transaction_count',
        'avg_spend',
        'spending_volatility'
    ]
].head()

,client_id,wellness_score,transaction_count,avg_spend,spending_volatility
0,0,77.554956,203,50.161330,93.467215
1,1,56.570928,145,39.595172,66.538118
2,2,63.958180,160,28.948000,43.631100
3,3,49.448066,98,48.028673,20.802682
4,4,76.598862,194,41.030309,66.551152

In [89]:
customer_metrics['wellness_category'] = pd.cut(
    customer_metrics['wellness_score'],
    bins=[-1000,50,100,200,10000],
    labels=[
        'Low Wellness',
        'Moderate Wellness',
        'Healthy',
        'Excellent'
    ]
)

In [90]:
customer_metrics['wellness_category'].value_counts()

wellness_category
Moderate Wellness    582
Low Wellness         489
Healthy              140
Excellent              8
Name: count, dtype: int64

In [91]:
customer_metrics['high_value_customer'] = np.where(customer_metrics['total_spend'] > 15000,1,0)

In [92]:
digital_usage = transactions.groupby('client_id')['use_chip'].apply(lambda x: (x.str.contains('Online', case=False)).mean()).reset_index()

In [93]:
digital_usage.columns = [
    'client_id',
    'digital_transaction_ratio'
]

In [94]:
customer_metrics = customer_metrics.merge(
    digital_usage,
    on='client_id',
    how='left'
)

In [95]:
customer_metrics['digital_persona'] = np.where(
    customer_metrics['digital_transaction_ratio'] > 0.5,
    'Digital First',
    'Traditional User'
)

In [96]:
customer_metrics['digital_persona'].value_counts()

digital_persona
Traditional User    1191
Digital First         28
Name: count, dtype: int64

In [97]:
last_transaction = transactions.groupby('client_id')['date'].max().reset_index()

In [98]:
last_transaction.columns = [
    'client_id',
    'last_transaction_date'
]

In [99]:
customer_metrics = customer_metrics.merge(
    last_transaction,
    on='client_id',
    how='left'
)

In [102]:
latest_date = transactions['date'].max()
customer_metrics['days_since_last_transaction'] = (latest_date - customer_metrics['last_transaction_date']).dt.days

In [103]:
customer_metrics['churn_risk'] = np.where(
    customer_metrics['days_since_last_transaction'] > 30,
    'High Risk',
    'Active'
)

In [104]:
customer_metrics['churn_risk'].value_counts()

churn_risk
Active       855
High Risk    364
Name: count, dtype: int64

In [107]:
customer_analytics = customer_metrics.merge(
    users,
    left_on='client_id',
    right_on='id',
    how='left'
)

In [106]:
customer_analytics.head()

,client_id,total_spend,avg_spend,transaction_count,spending_volatility,engagement_score,spending_tier,volatility_level,wellness_score,wellness_category,...,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,0,10182.75,50.161330,203,93.467215,141.864532,High Spender,Moderate,77.554956,Moderate Wellness,...,3,Male,858 Plum Avenue,43.59,-70.33,29237.0,59613.0,36199.0,763,4
1,1,5741.30,39.595172,145,66.538118,102.838069,Moderate Spender,Moderate,56.570928,Moderate Wellness,...,4,Female,113 Burns Lane,30.44,-87.18,22247.0,45360.0,14587.0,704,3
2,2,4631.68,28.948000,160,43.631100,107.579200,Moderate Spender,Stable,63.958180,Moderate Wellness,...,8,Male,6035 Forest Avenue,40.84,-73.87,13461.0,27447.0,80850.0,673,5
3,3,4706.81,48.028673,98,20.802682,78.011469,Moderate Spender,Stable,49.448066,Low Wellness,...,12,Male,840 Elm Avenue,33.89,-98.51,13705.0,27943.0,18693.0,681,4
4,4,7959.88,41.030309,194,66.551152,132.812124,High Spender,Moderate,76.598862,Moderate Wellness,...,3,Female,6016 Little Creek Boulevard,47.61,-122.30,37485.0,76431.0,115362.0,716,5

In [108]:
customer_analytics.columns

Index(['client_id', 'total_spend', 'avg_spend', 'transaction_count',
       'spending_volatility', 'engagement_score', 'spending_tier',
       'volatility_level', 'wellness_score', 'wellness_category',
       'high_value_customer', 'digital_transaction_ratio', 'digital_persona',
       'last_transaction_date', 'days_since_last_transaction', 'churn_risk',
       'id', 'current_age', 'retirement_age', 'birth_year', 'birth_month',
       'gender', 'address', 'latitude', 'longitude', 'per_capita_income',
       'yearly_income', 'total_debt', 'credit_score', 'num_credit_cards'],
      dtype='object')

In [109]:
users.to_csv(
    'users_cleaned.csv',
    index=False
)

cards.to_csv(
    'cards_cleaned.csv',
    index=False
)

transactions.to_csv(
    'transactions_cleaned.csv',
    index=False
)

customer_metrics.to_csv(
    'customer_metrics.csv',
    index=False
)

customer_analytics.to_csv(
    'customer_analytics.csv',
    index=False
)

In [110]:
from google.colab import files
files.download('customer_analytics.csv')
files.download('customer_metrics.csv')
files.download('transactions_cleaned.csv')
files.download('cards_cleaned.csv')
files.download('users_cleaned.csv')